apiVersion: v1
kind: Pod
metadata:
  name: keno-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    env:
    - name: DB_CONNECT
      valueFrom:
            configMapKeyRef:
              name: keno-env
              key: DB_URL
